# fly.toml app configuration file generated for axum-htmx-todo on 2024-07-17T00:49:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axum-htmx-todo'
primary_region = 'ord'

[build]

[env]
PORT = '8080'
RUST_LOG = 'info'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
